### ISSUE TITLE
Message text is cut off at top

### ISSUE THREAD

**Issue by saldous** [dkcas11/CRNotifications#8]
Example below:
<img width="698" alt="cutoff" src="https://user-images.githubusercontent.com/3334306/31058875-62a1813a-a6c9-11e7-9c9f-6cf08ba6e4e0.png">

**Comment by dkcas11** [comment]
Thanks, i will have a look :)

**Comment by dkcas11** [comment]
This has now been fixed in version 1.1.1.

**Comment by saldous** [comment]
Thanks, still not right.  I updated to 1.1.2 and see this:
![image](https://user-images.githubusercontent.com/3334306/31180499-d03fdb40-a8ec-11e7-8b5f-7d67f89fc4bb.png)

**Comment by dkcas11** [comment]
Which device are you using? Is this on the simulator?

**Comment by saldous** [comment]
iPhone X in simulator was that specific test.
